
/* Copyright (c) 2016-2017 Stanford University
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef BUFFER_STUFFER
#define BUFFER_STUFFER

#include <fstream>
#include <cstdarg>

#include <stdint.h>

/**
 * This header declares the structures generated by the NanoLog Preprocessor
 * for the NanoLog runtime compression thread and LogDecompressor to use.
 */

namespace GeneratedFunctions {
/**
 * Describes a log message found in the user sources by the original format
 * string provided, the file and line number of where the message occurred.
 */
struct LogMetadata {
  const char *fmtString;
  const char *fileName;
  uint32_t lineNumber;
};

/**
 * Size of the arrays below, defined by the number of unique LogIds in the
 * system. LogIds are assigned to each unique combination of log format string
 *  and filename/line number combination. The first valid id is 0 and the last
 * is (numLogIds-1).
 */
extern size_t numLogIds;

// Maps unique logIds to the metadata associated with the log (see LogMetadata)
extern struct LogMetadata logId2Metadata[];

/**
 * Map of unique logIds to the compression function that takes an
 * UncompressedLogEntry from the StagingBuffer and compresses it to buffer out.
 *
 * \param re
 *          Pointer to an UncomrpessedLogEntry within a StagingBuffer.
 * \param[out] out
 *          An output buffer to write the compressed log entry to
 *
 * \return
 *      The number of bytes written to *out
 */
extern ssize_t
(*compressFnArray[]) (BufferUtils::UncompressedLogEntry *re, char *out);


/**
 * Map of unique logIds to the decompression function that takes an input stream
 * (whose next bytes contain a compressed log) and prints the original log
 * output to outputFd. An optional aggregator function can be passed in to
 * interpret the results.
 *
 * \param in
 *      Input stream whose next bytes contain a compressed log corresponding
 *      to logId index..
 * \param outputFd
 *      File descriptor to print the original log message to. Set to NULL for
 *      no output.
 * \param[optional] aggFn
 *      Optional va_arg-style function used to aggregate the results.
 */
extern void
(*decompressAndPrintFnArray[]) (std::ifstream &in,
                                    FILE *outputFd,
                                    void (*aggFn)(char*, ...));

} // namespace GeneratedFunctions

#endif /* BUFFER_STUFFER */
